#!/bin/bash

if [ $# == 1 ] ; then
	if [ $1 == "copy" ] ; then
		echo "Copiere"
		mkdir "backup"
		for file in $(ls); do
			echo $file
			if [ !$file == "backup" ] ; then
				cp -rf $file "./backup"
			fi
		done
	else
		echo "Altceva"
	fi
else
	echo "Altceva"
fi
